export const GET_LOGIN_USER_DATA = "GET_LOGIN_USER_DATA";

export const SET_LOGIN_USER_DATA = "SET_LOGIN_USER_DATA";

export const SAVE_USER = "SAVE_USER";

export const LOGIN_WITH_PWD = "LOGIN_WITH_PWD";

