export const SELECT_ARTICLE_PAGE_DATA = "SELECT_ARTICLE_PAGE_DATA";
export const SELECT_NEXT_ARTICLE_PAGE_DATA = "SELECT_NEXT_ARTICLE_PAGE_DATA";
export const GET_RECOMMEND_LIST = "GET_RECOMMEND_LIST";
export const HAVE_MORE_PAGES = "HAVE_MORE_PAGES";
export const FIND_ARTICLE_BY_ID = "FIND_ARTICLE_BY_ID";
export const GET_VIEW_ARTICLE_DATA = "GET_VIEW_ARTICLE_DATA";